---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config.yaml
  - knative-kafka.yaml
  - knative-service.yaml
  - deployment-minio-event-bridge.yaml
  - service-minio-event-bridge.yaml
  - trigger.yaml
  - rbac.yaml
  - networkpolicy.yaml
