# Default values for workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: user1

workbench: my-workbench

repo: https://github.com/cnuland/hello-chris-rag-pipeline.git

subdomain: apps.cluster-guid.sandbox.opentlc.com

litellmKey: ""

minio:
  user: minio
  pass: minio123
  host: minio.minio.svc.cluster.local:9000
  bucket: user1
  route_prefix: minio-s3-minio
